name: Fetch and Build

on:
    push:
        branches:
            - master
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron:  '* 9,15,20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      run: |
        pip3 install requests
    - name: Fetch and Build
      run: |
        python fetch.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./data